const ENUM_LOGIN_ACTION_TYPES = {
    SET_FIELD_VALUE: 0,
    SET_FIELD_IS_TOUCHED: 1,
    SET_FIELD_ERROR: 2,
    CLEAR_FIELD_ERROR: 3,
    VALIDATED_FORM: 4,
    RESET_STATE: 5
}

export { ENUM_LOGIN_ACTION_TYPES }
