const ENUM_REGISTER_ACTION_TYPES = {
  SET_FIELD_VALUE: 0,
  SET_FIELD_IS_TOUCHED: 1,
  SET_FIELD_ERROR: 2,
  CLEAR_FIELD_ERROR: 3,
  VALIDATED_FORM: 4,
  CHECK_PASSWORD_CONFIRMATION: 5, // New action type
  RESET_STATE: 6,
  SET_SERVER_ERROR_MESSAGE: 7, // New action type
  SET_STATUS: 8, // New action type
};

export { ENUM_REGISTER_ACTION_TYPES };
